language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - main

script:
  - echo "test if deploy"
  - LATEST_COMMIT=$(git log -1 --format=format:%H --full-diff .)
  - LATEST_SITE_COMMIT=$(git log -1 --format=format:%H --full-diff ./captcha-service/test)
  - |
    if [[ $LATEST_COMMIT == $LATEST_SITE_COMMIT ]]
    then
      echo "Deploy Test Site"
      DEPLOY_SITE=true
    fi

after_script:
  - |
    if [[ $DEPLOY_SITE = true ]]
    then
      echo "Deploying Test Site"

      git config user.name $GHUSER
      git config user.email $GHEMAIL

      git checkout --orphan gh-pages
      git rm --cached -rf .

      mv captcha-service/test/*.* .
      rm -rf 1984 captcha-service

      git add index.* 1984.* refresh.svg
      git commit -m "update site"
      git remote add origin-pages https://thiagohersan:$GHTOKEN@github.com/thiagohersan/captcha-ocr.git
      git push origin-pages :gh-pages
      git push -u origin-pages gh-pages
    fi
