org: thersan
app: captcha-ocr
service: captcha-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  layers:
    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:22
  memorySize: 640
  timeout: 16
  environment:
    CORS_ORIGINS: ${param:CORS_ORIGINS}
    THE_ANSWER: ${param:THE_ANSWER}

functions:
  image:
    handler: service/functions/captcha.image
    events:
      - http:
          method: get
          cors: true
          path: /captcha
    environment:
      CAPTCHA_URL: http://${self:custom.s3BucketName}.s3-website-${self:provider.region}.amazonaws.com/
      CAPTCHA_SELECTORS: ${param:CAPTCHA_SELECTORS}

  compare:
    handler: service/functions/captcha.compare
    events:
      - http:
          method: post
          cors: true
          path: /captcha
          request:
            schemas:
              application/json: ${file(service/schema/compare_phrase_request.json)}
    environment:
      SUCCESS_URL: ${param:SUCCESS_URL}

resources:
  Resources:
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    ## Specifying the policies to make sure all files inside the Bucket are avaialble to CloudFront
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.s3BucketName}/*

custom:
  s3BucketName: captcha-service-gen
  s3Sync:
    - bucketName: ${self:custom.s3BucketName}
      localDir: app/

plugins:
  - serverless-mocha
  - serverless-export-env
  - serverless-s3-sync
