org: thersan
app: captcha-ocr
service: captcha-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  layers:
    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:22
  memorySize: 640
  timeout: 16

functions:
  image:
    handler: src/functions/captcha.image
    events:
      - http:
          method: get
          cors: true
          path: /captcha
    environment:
      CAPTCHA_URL: ${param:CAPTCHA_URL}
      CAPTCHA_SELECTORS: ${param:CAPTCHA_SELECTORS}
      THE_ANSWER: ${param:THE_ANSWER}

  compare:
    handler: src/functions/captcha.compare
    events:
      - http:
          method: post
          cors: true
          path: /captcha
          request:
            schemas:
              application/json: ${file(src/schema/compare_phrase_request.json)}
    environment:
      SUCCESS_URL: ${param:SUCCESS_URL}
      THE_ANSWER: ${param:THE_ANSWER}

custom:
  s3Bucket: captcha-service-gen

plugins:
  - serverless-pseudo-parameters
  - serverless-mocha
  - serverless-export-env
  - serverless-single-page-app-plugin
