name: deploy gh-pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '1984/**'
      - '.gitignore'
      - 'captcha-service/app/**'
      - 'captcha-service/service/**'
      - 'captcha-service/package*json'
      - 'captcha-service/serverless.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./captcha-service/test
          publish_branch: gh-pages
